version: '3.3'


services:
  postgres:
    restart: always
    hostname: postgres
    networks:
      - mynet
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tammytanuka
      PGDATA: /data/postgres2
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  web:
    restart: always
    build: .
    container_name: bot
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - mynet

networks:
  mynet:
    {}

volumes:
  postgres-db:
    driver: local