version: '3.5'


services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      POSTGRES_DB: tammytanuka
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  web:
    container_name: bot
    command: python main.py
    ports:
      - "80:80"


volumes:
  postgres-db:
    driver: local